# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `coffee-script-source` gem.
# Please instead update this file by running `tapioca sync`.

# typed: strict

module CoffeeScript
  class << self
    def compile(script, options = T.unsafe(nil)); end
    def engine; end
    def engine=(engine); end
    def version; end
  end
end

CoffeeScript::CompilationError = ExecJS::ProgramError

CoffeeScript::EngineError = ExecJS::RuntimeError

CoffeeScript::Error = ExecJS::Error

module CoffeeScript::Source
  class << self
    def bare_option; end
    def bundled_path; end
    def contents; end
    def context; end
    def path; end
    def path=(path); end
    def version; end
  end
end

CoffeeScript::Source::COMPILE_FUNCTION_SOURCE = T.let(T.unsafe(nil), String)
