# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `coffee-rails` gem.
# Please instead update this file by running `tapioca sync`.

# typed: strict

module Coffee
end

module Coffee::Rails
end

class Coffee::Rails::Engine < ::Rails::Engine
end

module Coffee::Rails::JsHook
  extend(::ActiveSupport::Concern)
end

class Coffee::Rails::TemplateHandler
  class << self
    def call(template, source = T.unsafe(nil)); end
    def erb_handler; end
  end
end

Coffee::Rails::VERSION = T.let(T.unsafe(nil), String)
