# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `erubis` gem.
# Please instead update this file by running `tapioca sync`.

# typed: strict

module Erubis
end

module Erubis::PI
end

class Erubis::PI::TinyEruby
  def initialize(input = T.unsafe(nil), options = T.unsafe(nil)); end

  def convert(input); end
  def evaluate(_context = T.unsafe(nil)); end
  def result(_binding = T.unsafe(nil)); end
  def src; end
end

Erubis::PI::TinyEruby::EMBEDDED_PATTERN = T.let(T.unsafe(nil), Regexp)

class Erubis::TinyEruby
  def initialize(input = T.unsafe(nil)); end

  def convert(input); end
  def evaluate(_context = T.unsafe(nil)); end
  def result(_binding = T.unsafe(nil)); end
  def src; end
end

Erubis::TinyEruby::EMBEDDED_PATTERN = T.let(T.unsafe(nil), Regexp)
