# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/faraday_middleware/all/faraday_middleware.rbi
#
# faraday_middleware-0.13.0
module Faraday
end
class Faraday::Request < Anonymous_Struct_27
end
class Faraday::Response
end
module FaradayMiddleware
end
