# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/letter_opener/all/letter_opener.rbi
#
# letter_opener-1.6.0
module LetterOpener
  def self.configuration; end
  def self.configure; end
end
class LetterOpener::Railtie < Rails::Railtie
end
