# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `letter_opener` gem.
# Please instead update this file by running `tapioca sync`.

# typed: strict

module LetterOpener
  class << self
    def configuration; end
    def configure; end
  end
end

class LetterOpener::Configuration
  def initialize; end

  def location; end
  def location=(_arg0); end
  def message_template; end
  def message_template=(_arg0); end
end

class LetterOpener::DeliveryMethod
  def initialize(options = T.unsafe(nil)); end

  def deliver!(mail); end
  def settings; end
  def settings=(_arg0); end

  private

  def validate_mail!(mail); end
end

class LetterOpener::DeliveryMethod::InvalidOption < ::StandardError
end

class LetterOpener::Message
  def initialize(mail, options = T.unsafe(nil)); end

  def <=>(other); end
  def attachment_filename(attachment); end
  def auto_link(text); end
  def bcc; end
  def body; end
  def cc; end
  def content_type; end
  def encoding; end
  def filepath; end
  def from; end
  def h(content); end
  def mail; end
  def render; end
  def reply_to; end
  def sender; end
  def template; end
  def to; end
  def type; end

  class << self
    def rendered_messages(mail, options = T.unsafe(nil)); end
  end
end

LetterOpener::Message::ERROR_MSG = T.let(T.unsafe(nil), String)

class LetterOpener::Railtie < ::Rails::Railtie
end
