# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `msgpack` gem.
# Please instead update this file by running `tapioca sync`.

# typed: strict

class Symbol
  include(::Comparable)

  def to_msgpack_ext; end

  class << self
    def from_msgpack_ext(data); end
  end
end
