# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sidekiq` gem.
# Please instead update this file by running `tapioca sync`.

# typed: true

module Sidekiq
  class << self
    def average_scheduled_poll_interval=(interval); end
    def client_middleware; end
    def configure_client; end
    def configure_server; end
    def death_handlers; end
    def default_server_middleware; end
    def default_worker_options; end
    def default_worker_options=(hash); end
    def dump_json(object); end
    def error_handlers; end
    def load_json(string); end
    def log_formatter; end
    def log_formatter=(log_formatter); end
    def logger; end
    def logger=(logger); end
    def on(event, &block); end
    def options; end
    def options=(opts); end
    def pro?; end
    def redis; end
    def redis=(hash); end
    def redis_info; end
    def redis_pool; end
    def server?; end
    def server_middleware; end
  end
end

class Sidekiq::Client
  def initialize(redis_pool = T.unsafe(nil)); end

  def middleware(&block); end
  def push(item); end
  def push_bulk(items); end
  def redis_pool; end
  def redis_pool=(_arg0); end

  private

  def atomic_push(conn, payloads); end
  def normalize_item(item); end
  def normalized_hash(item_class); end
  def process_single(worker_class, item); end
  def raw_push(payloads); end
  def validate(item); end

  class << self
    def enqueue(klass, *args); end
    def enqueue_in(interval, klass, *args); end
    def enqueue_to(queue, klass, *args); end
    def enqueue_to_in(queue, interval, klass, *args); end
    def push(item); end
    def push_bulk(items); end
    def via(pool); end
  end
end

module Sidekiq::Context
  class << self
    def current; end
    def with(hash); end
  end
end

Sidekiq::DEFAULTS = T.let(T.unsafe(nil), Hash)

Sidekiq::DEFAULT_WORKER_OPTIONS = T.let(T.unsafe(nil), Hash)

class Sidekiq::DeadSet < ::Sidekiq::JobSet
  def initialize; end

  def kill(message, opts = T.unsafe(nil)); end
  def retry_all; end

  class << self
    def max_jobs; end
    def timeout; end
  end
end

module Sidekiq::Extensions
  class << self
    def enable_delay!; end
  end
end

module Sidekiq::Extensions::PsychAutoload
  def resolve_class(klass_name); end
end

Sidekiq::FAKE_INFO = T.let(T.unsafe(nil), Hash)

class Sidekiq::Job
  include(::Sidekiq::Job::UniqueExtension)

  def initialize(item, queue_name = T.unsafe(nil)); end

  def [](name); end
  def args; end
  def created_at; end
  def delete; end
  def delete_orig; end
  def display_args; end
  def display_class; end
  def enqueued_at; end
  def error_backtrace; end
  def item; end
  def jid; end
  def klass; end
  def latency; end
  def parse(item); end
  def queue; end
  def tags; end
  def value; end

  private

  def safe_load(content, default); end
  def uncompress_backtrace(backtrace); end
end

class Sidekiq::JobSet < ::Sidekiq::SortedSet
  include(::Sidekiq::JobSet::UniqueExtension)

  def clear; end
  def clear_orig; end
  def delete(score, jid); end
  def delete_by_jid(score, jid); end
  def delete_by_value(name, value); end
  def delete_by_value_orig(name, value); end
  def each; end
  def fetch(score, jid = T.unsafe(nil)); end
  def find_job(jid); end
  def schedule(timestamp, message); end
end

Sidekiq::LICENSE = T.let(T.unsafe(nil), String)

class Sidekiq::Logger < ::Logger
  include(::Sidekiq::LoggingUtils)

  def initialize(*args, **kwargs); end
end

module Sidekiq::Logger::Formatters
end

class Sidekiq::Logger::Formatters::Base < ::Logger::Formatter
  def ctx; end
  def format_context; end
  def tid; end
end

class Sidekiq::Logger::Formatters::JSON < ::Sidekiq::Logger::Formatters::Base
  def call(severity, time, program_name, message); end
end

class Sidekiq::Logger::Formatters::Pretty < ::Sidekiq::Logger::Formatters::Base
  def call(severity, time, program_name, message); end
end

class Sidekiq::Logger::Formatters::WithoutTimestamp < ::Sidekiq::Logger::Formatters::Pretty
  def call(severity, time, program_name, message); end
end

module Sidekiq::LoggingUtils
  def add(severity, message = T.unsafe(nil), progname = T.unsafe(nil), &block); end
  def debug?; end
  def error?; end
  def fatal?; end
  def info?; end
  def level; end
  def local_level; end
  def local_level=(level); end
  def log_at(level); end
  def warn?; end
end

Sidekiq::LoggingUtils::LEVELS = T.let(T.unsafe(nil), Hash)

module Sidekiq::Middleware
end

class Sidekiq::Middleware::Chain
  include(::Enumerable)

  def initialize; end

  def add(klass, *args); end
  def clear; end
  def each(&block); end
  def empty?; end
  def entries; end
  def exists?(klass); end
  def insert_after(oldklass, newklass, *args); end
  def insert_before(oldklass, newklass, *args); end
  def invoke(*args); end
  def prepend(klass, *args); end
  def remove(klass); end
  def retrieve; end

  private

  def initialize_copy(copy); end
end

class Sidekiq::Middleware::Entry
  def initialize(klass, *args); end

  def klass; end
  def make_new; end
end

Sidekiq::NAME = T.let(T.unsafe(nil), String)

class Sidekiq::Process
  def initialize(hash); end

  def [](key); end
  def dump_threads; end
  def identity; end
  def labels; end
  def quiet!; end
  def stop!; end
  def stopping?; end
  def tag; end

  private

  def signal(sig); end
end

class Sidekiq::ProcessSet
  include(::Enumerable)

  def initialize(clean_plz = T.unsafe(nil)); end

  def cleanup; end
  def each; end
  def leader; end
  def size; end
end

class Sidekiq::Queue
  include(::Enumerable)
  include(::Sidekiq::Queue::UniqueExtension)

  def initialize(name = T.unsafe(nil)); end

  def clear; end
  def clear_orig; end
  def each; end
  def find_job(jid); end
  def latency; end
  def name; end
  def paused?; end
  def size; end

  class << self
    def all; end
  end
end

class Sidekiq::Rails < ::Rails::Engine
end

class Sidekiq::Rails::Reloader
  def initialize(app = T.unsafe(nil)); end

  def call; end
  def inspect; end
end

class Sidekiq::RedisConnection
  class << self
    def create(options = T.unsafe(nil)); end

    private

    def build_client(options); end
    def client_opts(options); end
    def determine_redis_provider; end
    def log_info(options); end
    def verify_sizing(size, concurrency); end
  end
end

class Sidekiq::RetrySet < ::Sidekiq::JobSet
  def initialize; end

  def kill_all; end
  def retry_all; end
end

class Sidekiq::ScheduledSet < ::Sidekiq::JobSet
  include(::Sidekiq::ScheduledSet::UniqueExtension)

  def initialize; end

  def delete; end
  def delete_orig(score, jid); end
end

class Sidekiq::Shutdown < ::Interrupt
end

class Sidekiq::SortedEntry < ::Sidekiq::Job
  include(::Sidekiq::SortedEntry::UniqueExtension)

  def initialize(parent, score, item); end

  def add_to_queue; end
  def at; end
  def delete; end
  def delete_orig; end
  def error?; end
  def kill; end
  def parent; end
  def reschedule(at); end
  def retry; end
  def score; end

  private

  def remove_job; end
  def remove_job_orig; end
end

class Sidekiq::SortedSet
  include(::Enumerable)

  def initialize(name); end

  def clear; end
  def name; end
  def scan(match, count = T.unsafe(nil)); end
  def size; end
end

class Sidekiq::Stats
  def initialize; end

  def dead_size; end
  def default_queue_latency; end
  def enqueued; end
  def failed; end
  def fetch_stats!; end
  def processed; end
  def processes_size; end
  def queues; end
  def reset(*stats); end
  def retry_size; end
  def scheduled_size; end
  def workers_size; end

  private

  def stat(s); end
end

class Sidekiq::Stats::History
  def initialize(days_previous, start_date = T.unsafe(nil)); end

  def failed; end
  def processed; end

  private

  def date_stat_hash(stat); end
end

class Sidekiq::Stats::Queues
  def lengths; end
end

Sidekiq::VERSION = T.let(T.unsafe(nil), String)

module Sidekiq::Worker
  include(::Sidekiq::Worker::Options)

  mixes_in_class_methods(::Sidekiq::Worker::ClassMethods)

  def jid; end
  def jid=(_arg0); end
  def logger; end

  class << self
    def included(base); end
  end
end

module Sidekiq::Worker::ClassMethods
  def client_push(item); end
  def delay(*args); end
  def delay_for(*args); end
  def delay_until(*args); end
  def perform_async(*args); end
  def perform_at(interval, *args); end
  def perform_in(interval, *args); end
  def set(options); end
  def sidekiq_options(opts = T.unsafe(nil)); end
end

module Sidekiq::Worker::Options
  mixes_in_class_methods(::Sidekiq::Worker::Options::ClassMethods)

  class << self
    def included(base); end
  end
end

module Sidekiq::Worker::Options::ClassMethods
  def get_sidekiq_options; end
  def sidekiq_class_attribute(*attrs); end
  def sidekiq_options(opts = T.unsafe(nil)); end
  def sidekiq_retries_exhausted(&block); end
  def sidekiq_retry_in(&block); end
end

Sidekiq::Worker::Options::ClassMethods::ACCESSOR_MUTEX = T.let(T.unsafe(nil), Thread::Mutex)

class Sidekiq::Worker::Setter
  def initialize(klass, opts); end

  def perform_async(*args); end
  def perform_at(interval, *args); end
  def perform_in(interval, *args); end
  def set(options); end
end

class Sidekiq::Workers
  include(::Enumerable)

  def each(&block); end
  def size; end
end
