# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tzinfo-data` gem.
# Please instead update this file by running `tapioca sync`.

# typed: strict

module TZInfo
end

module TZInfo::Data
end

TZInfo::Data::VERSION = T.let(T.unsafe(nil), String)

module TZInfo::Data::Version
end

TZInfo::Data::Version::FORMAT = T.let(T.unsafe(nil), Integer)

TZInfo::Data::Version::STRING = T.let(T.unsafe(nil), String)

TZInfo::Data::Version::TZDATA = T.let(T.unsafe(nil), String)

TZInfo::VERSION = T.let(T.unsafe(nil), String)
