# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActionView::Helpers`.
# Please instead update this file by running `tapioca dsl --gen UrlHelpers`.

# typed: strict
module ActionView
  module Helpers
    include GeneratedPathHelpersModule
    include GeneratedUrlHelpersModule
  end
end