# typed: strong
# This is an autogenerated file for Rails helpers.
# Please rerun rake rails_rbi:mailers to regenerate.
class SummaryMailer
  sig { params(user: T.untyped).returns(ActionMailer::MessageDelivery) }
  def self.new_reviews(user); end

  sig { params(user: T.untyped).returns(ActionMailer::MessageDelivery) }
  def self.pending_reviews_summary(user); end
end
