# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ApplicationMailer`.
# Please instead update this file by running `tapioca dsl`.

# typed: strict
class ApplicationMailer
  include GeneratedUrlHelpersModule

  sig { returns(::ActionMailer::MessageDelivery) }
  def self.default_url_options; end
end