# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `tapioca todo`.

# typed: strict

module ::SimpleCov; end
module ::SimpleCov::Formatter::Codecov; end
module Erubis::Eruby; end
module Sidekiq::Extensions::DelayedClass; end
